runmode = 'dev'

[redis]
# address = "49.233.192.84:16379"
# address = "192.168.2.181:6379"
address = "192.168.2.25:6379"
timeout = 500
pwd = "QAZxswZXC"

[influx]
enabled = false
url = "http://127.0.0.1:8086"
token = ""
org = "iot"
bucket = "device_history"
timeout_seconds = 3
